dbot recommendations and gemspec/gemfile updates
urbanopt/urbanopt-scenario-gem pull request #151
Opened 2020-09-17 22:13 UTC by vtnate

### Addresses dbot recommendations
### Pull Request Description
- update dependencies on dbots recommendations
- update gemspec as reasonable, while still pointing at develop branches with gemfile for those gems that have updates beyond the released version
### Checklist (Delete lines that don't apply)

- [ ] All ci tests pass (green)
- [ ] This branch is up-to-date with develop

2020-09-18 05:04 UTC, kflemin requested changes

2020-09-18 05:04 UTC, kflemin commented on urbanopt-scenario-gem.gemspec
> +  spec.add_runtime_dependency 'openstudio-common-measures', '~> 0.2'
we need another digit on the openstudio/urbanopt gems...i'm not comfortable allowing upgrades on such a wide range.  thanks!

2020-09-18 14:58 UTC, kflemin approved these changes

2020-09-18 15:04 UTC, merged

2020-09-21 14:02 UTC, vtnate commented on urbanopt-scenario-gem.gemspec
> +  # spec.add_runtime_dependency 'urbanopt-reporting', '~> 0.1.1'
Eeek! Sorry! I'll fix that. I thought the Gemfile would supersede the gemspec, so I required those gems from there.